import { useEffect, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { api, compactMoney, formatDate, isDemoMode, money } from './api';
import { useAuth } from './auth';
import { BarChart, CoverageBars, DonutChart, LineChart } from './charts';
import { AuditPageV2, AnalystPageV2, InvestmentPageV2, ViewerDashboard } from './enhancements';

const navByRole = {
  admin: [
    { to: '/', label: 'Executive command', icon: '◈' }, { to: '/attacks', label: 'Live attacks', icon: '◉' },
    { to: '/assets', label: 'Asset risk', icon: '⌘' }, { to: '/vulnerabilities', label: 'Findings', icon: '△' },
    { to: '/investment', label: 'Investment lab', icon: '↗' }, { to: '/controls', label: 'Controls', icon: '◌' },
    { to: '/audit', label: 'Audit evidence', icon: '✓' }, { to: '/analyst', label: 'Analyst copilot', icon: '✦' },
  ],
  analyst: [
    { to: '/', label: 'Technical command', icon: '◈' }, { to: '/attacks', label: 'Live attacks', icon: '◉' },
    { to: '/assets', label: 'Asset risk', icon: '⌘' }, { to: '/vulnerabilities', label: 'Findings', icon: '△' },
    { to: '/incidents', label: 'Incidents', icon: '!' }, { to: '/analyst', label: 'Analyst copilot', icon: '✦' },
  ],
  viewer: [
    { to: '/', label: 'Board summary', icon: '◈' }, { to: '/assets', label: 'Asset risk', icon: '⌘' },
    { to: '/attacks', label: 'Attack watch', icon: '◉' }, { to: '/audit', label: 'Audit evidence', icon: '✓' },
  ],
};

const emptyData = { settings: {}, assets: [], vulnerabilities: [], controls: [], incidents: [], events: [], risks: [], audit: null, trend: [] };
const arr = (value) => Array.isArray(value) ? value : [];
const payload = (response) => response?.data ?? response ?? [];

function useWorkspaceData() {
  const { user } = useAuth();
  const [data, setData] = useState(emptyData);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [syncedAt, setSyncedAt] = useState(null);
  const refresh = async () => {
    setLoading(true); setError('');
    const results = await Promise.allSettled([api.settings(), api.assets(), api.vulnerabilities(), api.controls(), user.role === 'viewer' ? Promise.resolve({ data: [] }) : api.incidents(), api.events(), api.risks(), api.auditReport(), api.riskTrend()]);
    const [settings, assets, vulnerabilities, controls, incidents, events, risks, audit, trend] = results;
    setData({
      settings: settings.status === 'fulfilled' ? payload(settings.value) : {},
      assets: assets.status === 'fulfilled' ? arr(payload(assets.value)) : [],
      vulnerabilities: vulnerabilities.status === 'fulfilled' ? arr(payload(vulnerabilities.value)) : [],
      controls: controls.status === 'fulfilled' ? arr(payload(controls.value)) : [],
      incidents: incidents.status === 'fulfilled' ? arr(payload(incidents.value)) : [],
      events: events.status === 'fulfilled' ? arr(payload(events.value)) : [],
      risks: risks.status === 'fulfilled' ? arr(payload(risks.value)) : [],
      audit: audit.status === 'fulfilled' ? (audit.value?.report || payload(audit.value)) : null,
      trend: trend.status === 'fulfilled' ? arr(payload(trend.value)) : [],
    });
    const failure = results.find((result) => result.status === 'rejected');
    if (failure && !isDemoMode()) setError(failure.reason?.message || 'Some backend data is unavailable');
    setSyncedAt(new Date()); setLoading(false);
  };
  useEffect(() => { refresh(); }, []);
  useEffect(() => { const timer = setInterval(async () => { try { const result = await api.events(); setData((current) => ({ ...current, events: arr(payload(result)) })); } catch { /* retain last known event feed */ } }, 5000); return () => clearInterval(timer); }, []);
  return { data, loading, error, syncedAt, refresh };
}

function attackLabel(event) {
  const raw = `${event.event_type || ''} ${event.type || ''} ${event.raw_payload?.issue_name || ''}`.toLowerCase();
  if (/sql|injection/.test(raw)) return 'SQL injection attempt';
  if (/malware|ransom|trojan/.test(raw)) return 'Malware detected';
  if (/failed|brute|credential|login/.test(raw)) return 'Credential attack signal';
  if (/port|scan|recon/.test(raw)) return 'Network reconnaissance';
  if (/xss|cross.site/.test(raw)) return 'Cross-site scripting';
  if (/phish/.test(raw)) return 'Phishing signal';
  if (/vulnerab|cve|exploit/.test(raw)) return 'Exploitable vulnerability';
  return event.event_type || `${event.type || 'Unknown'} telemetry`;
}

function RiskBadge({ value }) { const normalized = String(value || 'unknown').toLowerCase().replaceAll(' ', '_'); return <span className={`risk-badge ${normalized}`}>{value || 'Unknown'}</span>; }
function Empty({ title, copy }) { return <div className="empty-state"><div className="empty-symbol">◌</div><h3>{title}</h3><p>{copy}</p></div>; }
function Metric({ label, value, detail, tone = 'teal' }) { return <div className={`metric-card ${tone}`}><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></div>; }

function LiveFeed({ events, full = false, onSimulate }) {
  const list = arr(events).slice(0, full ? 20 : 5);
  const newest = list[0];
  const live = newest && (Date.now() - new Date(newest.observed_at || newest.timestamp || newest.createdAt).getTime()) < 30000;
  return <section className={`panel live-feed-panel ${full ? 'full-feed' : ''}`}><div className="panel-heading"><div><p className="eyebrow">Continuous telemetry</p><h2>{full ? 'Attack watch' : 'Live attack monitor'}</h2><p className="panel-subtitle">Signals are evidence; confirmation remains an analyst decision.</p></div><div className="feed-actions"><span className={live ? 'live-indicator active' : 'live-indicator'}><span className="pulse-dot" />{live ? 'Live signal' : 'Monitoring'}</span>{isDemoMode() && onSimulate && <button className="button demo-button" onClick={onSimulate}>Simulate demo attack</button>}</div></div>{list.length ? <div className="attack-feed">{list.map((event, index) => <div className={index === 0 ? 'attack-row newest' : 'attack-row'} key={`${event._id || event.createdAt || event.timestamp}-${index}`}><div className="attack-severity"><span>{String(event.severity || 'info').slice(0, 1).toUpperCase()}</span></div><div className="attack-main"><strong>{attackLabel(event)}</strong><small>{event.source || event.type || 'telemetry'} · {event.asset_id || 'UNMAPPED'}{event.endpoint ? ` · ${event.endpoint}` : ''}{event.source_ip ? ` · ${event.source_ip}` : ''}</small></div><RiskBadge value={event.severity || 'info'} /><time>{formatDate(event.observed_at || event.timestamp || event.createdAt)}</time></div>)}</div> : <Empty title="No attack signal observed" copy="Send Wazuh, Burp, OpenVAS, Nmap, EDR, IAM, CSPM, or threat-intel telemetry to see the signal here." />}</section>;
}

function Shell({ children, syncedAt }) {
  const { user, signOut } = useAuth(); const location = useLocation(); const navigate = useNavigate(); const items = navByRole[user.role] || navByRole.viewer; const current = items.find((item) => item.to === location.pathname) || items[0];
  return <div className="app-shell"><aside className="sidebar"><div className="brand-lockup"><span className="brand-mark">A</span><span>Attack On Point</span></div><div className="sidebar-caption">Internal cyber risk command</div><div className="role-banner"><span className="role-dot" /><div><strong>{user.role === 'admin' ? 'Executive workspace' : user.role === 'analyst' ? 'Technical workspace' : 'Read-only workspace'}</strong><small>Role-based access active</small></div></div><nav className="side-nav">{items.map((item) => <NavLink key={item.to} to={item.to} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><span className="nav-icon">{item.icon}</span>{item.label}</NavLink>)}</nav><div className="sidebar-bottom"><div className="pipeline-status"><span className="pulse-dot" /><span><strong>Evidence pipeline live</strong><small>5 second event refresh</small></span></div><div className="user-chip"><span className="avatar">{user.name?.slice(0, 1).toUpperCase()}</span><span className="user-meta"><strong>{user.name}</strong><small>{user.role}{user.demo ? ' · demo' : ''}</small></span><button className="icon-button" title="Sign out" onClick={signOut}>↪</button></div></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">{user.role === 'admin' ? 'Board decision intelligence' : user.role === 'analyst' ? 'Security operations intelligence' : 'Board risk briefing'}</p><h1>{current.label}</h1></div><div className="topbar-actions"><span className="last-sync">{syncedAt ? `Synced ${formatDate(syncedAt)}` : 'Awaiting sync'}</span><button className="button ghost" onClick={() => window.location.reload()}>Refresh</button>{user.role === 'admin' && <button className="button primary" onClick={() => navigate('/investment')}>Model a decision <span>↗</span></button>}</div></header><div className="mobile-nav">{items.map((item) => <NavLink key={item.to} to={item.to} className={({ isActive }) => isActive ? 'mobile-nav-item active' : 'mobile-nav-item'}>{item.label}</NavLink>)}</div>{children}</main></div>;
}

function ExecutiveDashboard({ data, onSimulate }) {
  const settings = data.settings; const riskMap = Object.fromEntries(data.risks.map((item) => [item.asset_id, item])); const open = data.vulnerabilities.filter((item) => item.status !== 'fixed'); const severity = { critical: open.filter((x) => x.severity === 'critical').length, high: open.filter((x) => x.severity === 'high').length, medium: open.filter((x) => x.severity === 'medium').length, low: open.filter((x) => x.severity === 'low').length }; const top = data.assets.map((asset) => ({ ...asset, risk_score: riskMap[asset.asset_id]?.score || asset.risk_score || 0 })).sort((a, b) => b.risk_score - a.risk_score); const coverage = data.audit?.regulatory_compliance_breakdown || {};
  return <><section className="board-hero"><div><p className="eyebrow">Board risk briefing / live portfolio</p><h2>Make the exposure legible.</h2><p>One view from technical evidence to annual loss, investment choices, and governance proof.</p></div><div className="decision-banner"><span className="decision-kicker">Decision signal</span><strong>{compactMoney(settings.total_expected_annual_loss_inr)} annual exposure</strong><small>{data.controls.length} controls competing for {compactMoney(settings.enterprise_budget_inr)} budget</small></div></section><section className="metric-grid"><Metric label="Expected annual loss" value={compactMoney(settings.total_expected_annual_loss_inr)} detail="Portfolio financial exposure" tone="teal" /><Metric label="Value at risk" value={compactMoney(settings.value_at_risk_inr)} detail="Tail-loss estimate" tone="amber" /><Metric label="Budget available" value={compactMoney(settings.enterprise_budget_inr)} detail="Explicit investment constraint" tone="blue" /><Metric label="Priority findings" value={severity.critical + severity.high} detail={`${severity.critical} critical · ${severity.high} high`} tone="red" /></section><section className="chart-grid executive-charts"><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Portfolio trend</p><h2>Exposure is moving</h2></div><span className="chart-chip">INR</span></div><LineChart data={data.trend} label="EAL" /></div><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Concentration</p><h2>Risk by asset</h2></div></div><BarChart items={top} labelKey="hostname" valueKey="risk_score" /></div></section><section className="chart-grid executive-charts"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Finding mix</p><h2>What is driving attention</h2></div></div><DonutChart {...severity} /></div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Framework posture</p><h2>Coverage by framework</h2></div></div><CoverageBars frameworks={coverage} /></div></section><section className="content-grid two-col"><div className="panel decision-panel"><p className="eyebrow">Board takeaway</p><h2>The risk is concentrated, not abstract.</h2><p>Payment and identity assets carry the highest financial exposure. The decision is whether to fund patching and phishing-resistant MFA before adding lower-impact controls.</p><div className="takeaway-row"><span>Highest exposure</span><strong>{top[0]?.hostname || 'Not assessed'}</strong></div><div className="takeaway-row"><span>Recommended posture</span><strong>Fund the top 3 controls first</strong></div></div><LiveFeed events={data.events} onSimulate={onSimulate} /></section></>;
}

function TechnicalDashboard({ data, onSimulate }) {
  const open = data.vulnerabilities.filter((item) => item.status !== 'fixed'); const active = data.events.filter((item) => ['critical', 'high'].includes(String(item.severity).toLowerCase())); const kev = open.filter((item) => item.cisa_kev).length; const avgAge = open.length ? Math.round(open.reduce((sum, item) => sum + Number(item.patch_age_days || 0), 0) / open.length) : 0; const riskMap = Object.fromEntries(data.risks.map((item) => [item.asset_id, item])); const top = data.assets.map((asset) => ({ ...asset, risk_score: riskMap[asset.asset_id]?.score || asset.risk_score || 0 })).sort((a, b) => b.risk_score - a.risk_score);
  return <><section className="board-hero technical-hero"><div><p className="eyebrow">SOC view / evidence first</p><h2>What is happening right now?</h2><p>Investigate active attack signals, unpatched exposure, and the assets that translate technical severity into business loss.</p></div><div className="live-callout"><span className="pulse-dot" /><strong>{active.length} high-priority signals</strong><small>from the current telemetry window</small></div></section><section className="metric-grid"><Metric label="Active attack signals" value={active.length} detail="High or critical telemetry" tone="red" /><Metric label="KEV findings" value={kev} detail="Known exploited vulnerabilities" tone="amber" /><Metric label="Average patch age" value={`${avgAge}d`} detail="Open finding backlog" tone="blue" /><Metric label="Assets monitored" value={data.assets.length} detail="Business-linked inventory" tone="teal" /></section><LiveFeed events={data.events} onSimulate={onSimulate} /><section className="chart-grid executive-charts"><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Risk ranking</p><h2>Assets needing attention</h2></div></div><BarChart items={top} labelKey="hostname" valueKey="risk_score" color="#bf4a4a" /></div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Telemetry coverage</p><h2>Source activity</h2></div></div><div className="telemetry-grid">{['Wazuh', 'Burp Suite', 'OpenVAS', 'Nmap', 'EDR', 'IAM'].map((source) => <div className="telemetry-tile" key={source}><span>{source}</span><strong>{data.events.filter((event) => String(event.source || event.type).toLowerCase().includes(source.split(' ')[0].toLowerCase())).length}</strong><small>events</small></div>)}</div></div></section></>;
}

function AssetsPage({ data }) {
  const [selected, setSelected] = useState(null); const riskMap = Object.fromEntries(data.risks.map((item) => [item.asset_id, item]));
  return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">Business-linked inventory</p><h2>Asset risk register</h2><p>Technical findings are ranked by business criticality, exposure, dependencies, and financial impact.</p></div><span className="stat-chip">{data.assets.length} monitored assets</span></div><div className="table-panel"><table><thead><tr><th>Asset</th><th>Business unit</th><th>Criticality</th><th>Exposure</th><th>Risk score</th><th>Annual loss</th><th /></tr></thead><tbody>{data.assets.map((asset) => { const risk = riskMap[asset.asset_id] || {}; return <tr key={asset.asset_id}><td><strong>{asset.hostname || asset.asset_id}</strong><small>{asset.asset_id}</small></td><td>{asset.business_unit || 'Unassigned'}</td><td><RiskBadge value={asset.criticality} /></td><td>{asset.internet_exposed ? <span className="danger-text">Internet exposed</span> : <span className="muted">Internal</span>}</td><td><strong>{risk.score || asset.risk_score || 0}</strong><small>{risk.level || asset.risk_level || 'Not assessed'}</small></td><td>{compactMoney(risk.eal_inr || asset.asset_eal_inr)}</td><td><button className="table-action" onClick={() => setSelected({ asset, risk })}>Inspect</button></td></tr>; })}</tbody></table></div>{selected && <AssetDrawer {...selected} onClose={() => setSelected(null)} />}</section>;
}

function AssetDrawer({ asset, risk, onClose }) {
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={onClose}>×</button><p className="eyebrow">Asset drilldown</p><h2>{asset.hostname || asset.asset_id}</h2><p className="muted">{asset.asset_id} · {asset.business_unit}</p><div className="drawer-metrics"><div><small>Risk score</small><strong>{risk?.score || asset.risk_score || 0}</strong></div><div><small>Asset EAL</small><strong>{compactMoney(risk?.eal_inr || asset.asset_eal_inr)}</strong></div></div><div className="detail-list"><div><span>Criticality</span><RiskBadge value={asset.criticality} /></div><div><span>Exposure</span><strong>{asset.internet_exposed ? 'Internet exposed' : 'Internal'}</strong></div><div><span>Downtime cost</span><strong>{money(asset.hourly_downtime_cost_inr)}/hr</strong></div><div><span>Dependencies</span><strong>{asset.dependencies?.join(', ') || 'None'}</strong></div><div><span>Frameworks</span><strong>{asset.applicable_frameworks?.join(', ') || 'Not mapped'}</strong></div></div><div className="driver-list"><p className="eyebrow">Why this score?</p>{risk?.drivers?.length ? risk.drivers.map((driver, index) => <div className="driver-row" key={`${driver.factor}-${index}`}><span>{driver.factor}</span><strong>{Number(driver.contribution || 0).toFixed(2)}</strong><small>{driver.explanation || driver.source}</small></div>) : <div className="soft-note">Driver attribution will appear after the AI engine returns explanations.</div>}</div></aside></div>;
}

function VulnerabilitiesPage({ data }) {
  const [filter, setFilter] = useState('all'); const items = data.vulnerabilities.filter((item) => filter === 'all' || String(item.severity).toLowerCase() === filter);
  return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">Evidence inventory</p><h2>Vulnerabilities</h2><p>Exploitability, age, and business context instead of a severity-only queue.</p></div><div className="filter-tabs">{['all', 'critical', 'high', 'medium'].map((value) => <button key={value} className={filter === value ? 'filter-tab active' : 'filter-tab'} onClick={() => setFilter(value)}>{value}</button>)}</div></div><div className="table-panel"><table><thead><tr><th>Finding</th><th>Asset</th><th>CVSS</th><th>EPSS</th><th>Exploit signals</th><th>Age</th><th>Status</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.asset_id}-${item.cve}-${index}`}><td><strong>{item.cve || item.finding_type}</strong><small>{item.finding_type || 'finding'}</small></td><td>{item.asset_id}</td><td><span className="score-cell">{Number(item.cvss || 0).toFixed(1)}</span></td><td>{Number(item.epss || 0).toFixed(2)}</td><td><div className="signal-stack">{item.cisa_kev && <span className="signal danger">KEV</span>}{item.exploit_available && <span className="signal amber">Exploit</span>}</div></td><td>{item.patch_age_days || 0} days</td><td><RiskBadge value={item.status || item.severity} /></td></tr>)}</tbody></table></div></section>;
}

function ControlsPage({ data }) {
  return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">Control portfolio</p><h2>Controls and remediations</h2><p>Admin-only view of cost, effectiveness, ownership, and regulatory mapping.</p></div><span className="stat-chip">{data.controls.length} candidate controls</span></div><div className="control-grid">{data.controls.map((control) => <article className="control-card" key={control.control_id}><div className="control-top"><span className="control-id">{control.control_id}</span><RiskBadge value={control.status?.replaceAll('_', ' ')} /></div><h3>{control.name}</h3><p>{control.description || 'No description provided.'}</p><div className="control-stats"><div><small>Cost</small><strong>{compactMoney(control.cost_inr)}</strong></div><div><small>Reduction</small><strong>{control.risk_reduction_pct || 0}%</strong></div></div><div className="control-foot"><span>{control.owner || 'Unassigned'}</span><span>{control.compliance_frameworks?.join(' · ') || 'No framework map'}</span></div></article>)}</div></section>;
}

function AttacksPage({ data, onSimulate }) { return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">SOC and governance bridge</p><h2>Attack watch</h2><p>Recent telemetry translated into an explainable attack signal for both technical and executive users.</p></div></div><LiveFeed events={data.events} full onSimulate={onSimulate} /></section>; }

function InvestmentPage({ data }) {
  const [selected, setSelected] = useState([]); const [delay, setDelay] = useState(0); const [result, setResult] = useState(null); const [curve, setCurve] = useState([]); const [error, setError] = useState('');
  useEffect(() => { api.investmentCurve().then((response) => setCurve(arr(payload(response)))).catch((err) => setError(err.message)); }, []);
  const toggle = (id) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const run = async (event) => { event.preventDefault(); try { setResult(await api.whatIf({ simulated_control_ids: selected, delay_days: Number(delay) })); } catch (err) { setError(err.message); } };
  return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">Budget-constrained decision support</p><h2>Investment lab</h2><p>Show which controls earn their place under an explicit INR budget constraint.</p></div></div><div className="content-grid two-col"><form className="panel form-panel" onSubmit={run}><div className="panel-heading"><div><p className="eyebrow">What-if portfolio</p><h2>Select controls</h2></div><span className="stat-chip">Budget {compactMoney(data.settings.enterprise_budget_inr)}</span></div><label>Remediation delay days<input type="number" min="0" value={delay} onChange={(event) => setDelay(event.target.value)} /></label><div className="control-picker">{data.controls.map((control) => <label className={selected.includes(control.control_id) ? 'picker-row selected' : 'picker-row'} key={control.control_id}><input type="checkbox" checked={selected.includes(control.control_id)} onChange={() => toggle(control.control_id)} /><span><strong>{control.name}</strong><small>{control.control_id} · {compactMoney(control.cost_inr)} · {control.risk_reduction_pct}% reduction</small></span></label>)}</div>{error && <div className="error-box">{error}</div>}<button className="button primary full">Run what-if model</button></form><div className="panel result-panel"><div className="panel-heading"><div><p className="eyebrow">Financial output</p><h2>Decision delta</h2></div></div>{result ? <><div className="result-highlight"><small>Simulated EAL</small><strong>{compactMoney(result.simulated_eal_inr)}</strong><span>{Number(result.combined_reduction_pct || 0).toFixed(1)}% combined reduction</span></div><div className="result-grid"><div><small>Original EAL</small><strong>{compactMoney(result.original_eal_inr)}</strong></div><div><small>Risk delta</small><strong>{compactMoney(result.risk_reduction_achieved_inr)}</strong></div></div><p className="soft-note">{result.warning}</p></> : <Empty title="Choose a portfolio" copy="Select controls to see the modeled financial delta." />}</div></div><div className="panel curve-panel"><div className="panel-heading"><div><p className="eyebrow">Cost effectiveness</p><h2>Investment versus risk reduction</h2></div></div>{curve.map((point) => <div className="curve-row" key={point.control_id}><div className="curve-label"><strong>{point.name}</strong><small>{compactMoney(point.cost_inr)} cumulative · {Number(point.cumulative_risk_reduction_pct || 0).toFixed(1)}% reduction</small></div><div className="curve-track"><span style={{ width: `${Math.min(100, Number(point.cumulative_risk_reduction_pct || 0))}%` }} /></div><strong className={Number(point.estimated_rosi_pct) >= 0 ? 'positive-text' : 'danger-text'}>{Number(point.estimated_rosi_pct || 0).toFixed(0)}% ROSI</strong></div>)}</div></section>;
}

function AuditPage({ data }) {
  const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const verify = async () => { setBusy(true); try { setResult(await api.verifyAudit()); } catch (err) { setResult({ status: 'ERROR', message: err.message }); } finally { setBusy(false); } }; const summary = data.audit?.summary || {};
  return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">Governance evidence</p><h2>Audit trail</h2><p>Integrity proof for the risk report, not a generic compliance claim.</p></div><button className="button dark" onClick={verify}>{busy ? 'Verifying...' : 'Verify latest report'} <span>✓</span></button></div><div className="content-grid two-col"><div className="panel verification-panel"><div className="panel-heading"><div><p className="eyebrow">Integrity check</p><h2>{result?.status || 'Not checked'}</h2></div></div>{result ? <><div className={`verification-banner ${result.status === 'SECURE' ? 'secure' : 'warning'}`}><span>{result.status === 'SECURE' ? '✓' : '!'}</span><strong>{result.message}</strong></div><div className="hash-block"><span>Report hash</span><code>{result.report_hash || 'Unavailable'}</code><span>Transaction</span><code>{result.tx_hash || 'Unavailable'}</code></div></> : <Empty title="Verification not run" copy="Run the check to prove the current report is unchanged." />}</div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Report snapshot</p><h2>{data.audit?.organization || 'Current evidence'}</h2></div></div><div className="detail-list"><div><span>Generated</span><strong>{formatDate(data.audit?.report_generated_at)}</strong></div><div><span>Assets monitored</span><strong>{summary.total_assets_monitored ?? data.assets.length}</strong></div><div><span>Open vulnerabilities</span><strong>{summary.open_vulnerabilities_count ?? data.vulnerabilities.length}</strong></div><div><span>Critical unpatched CVEs</span><strong>{summary.critical_unpatched_cves ?? '—'}</strong></div><div><span>Interpretation</span><strong>Evidence integrity, not certification</strong></div></div></div></div></section>;
}

function AnalystPage() {
  const [query, setQuery] = useState(''); const [answer, setAnswer] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const ask = async (event) => { event.preventDefault(); if (!query.trim()) return; setBusy(true); setError(''); try { const result = await api.analystQuery({ query: query.trim() }); setAnswer(payload(result)); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">Local GenAI + RAG</p><h2>Analyst copilot</h2><p>This is an investigation surface. Board users receive the conclusion, analysts inspect the evidence behind it.</p></div></div><div className="copilot-grid"><div className="copilot-intro"><span className="copilot-orb">✦</span><h3>Ask the risk engine</h3><p>Queries are sent to the configured FastAPI/Ollama service in production. Demo mode returns a deterministic evidence-grounded answer.</p><div className="prompt-list">{['Which asset has the highest EAL and why?', 'Which control gives the best risk reduction per rupee?', 'Summarize the RBI-relevant exposure for the board.'].map((prompt) => <button key={prompt} onClick={() => setQuery(prompt)}>{prompt}<span>↗</span></button>)}</div></div><div className="chat-panel"><div className="chat-header"><span className="pulse-dot" /> Analyst service</div><div className="chat-body">{answer ? <div className="answer"><div className="answer-label">Answer</div><p>{answer.answer || answer.executive_summary || 'Structured response received.'}</p>{answer.recommended_actions?.length ? <div className="action-list"><strong>Recommended actions</strong>{answer.recommended_actions.map((action) => <span key={action}>✓ {action}</span>)}</div> : null}</div> : <div className="chat-placeholder"><span>✦</span><p>Your evidence-grounded answer will appear here.</p></div>}</div><form className="chat-form" onSubmit={ask}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask a business or technical question..." /><button className="button dark" disabled={busy}>{busy ? '...' : 'Ask'}</button></form>{error && <div className="error-box">{error}</div>}</div></div></section>;
}

function IncidentsPage({ data, onRefresh }) {
  const [form, setForm] = useState({ incident_id: '', asset_id: '', attack_type: '', compromise_status: 'suspected', affected_records: 0, total_records: 0, service_downtime_minutes: 0, evidence_confidence: .5 }); const [message, setMessage] = useState(''); const submit = async (event) => { event.preventDefault(); try { await api.createIncident({ ...form, affected_records: Number(form.affected_records), total_records: Number(form.total_records), service_downtime_minutes: Number(form.service_downtime_minutes), evidence_confidence: Number(form.evidence_confidence) }); setMessage('Incident logged.'); onRefresh(); } catch (err) { setMessage(err.message); } };
  return <section className="page-section"><div className="section-intro"><div><p className="eyebrow">Governance record</p><h2>Incident ledger</h2><p>Record impact evidence so future quantification improves.</p></div></div><div className="content-grid two-col"><form className="panel form-panel" onSubmit={submit}><div className="panel-heading"><div><p className="eyebrow">New record</p><h2>Log incident</h2></div></div><div className="form-grid"><label>Incident ID<input value={form.incident_id} onChange={(e) => setForm({ ...form, incident_id: e.target.value })} required placeholder="INC-2026-001" /></label><label>Asset ID<input value={form.asset_id} onChange={(e) => setForm({ ...form, asset_id: e.target.value })} required placeholder="AST-CORE-01" /></label><label>Attack type<input value={form.attack_type} onChange={(e) => setForm({ ...form, attack_type: e.target.value })} placeholder="Credential stuffing" /></label><label>Status<select value={form.compromise_status} onChange={(e) => setForm({ ...form, compromise_status: e.target.value })}><option>suspected</option><option>confirmed</option><option>contained</option><option>closed</option></select></label><label>Affected records<input type="number" min="0" value={form.affected_records} onChange={(e) => setForm({ ...form, affected_records: e.target.value })} /></label><label>Downtime minutes<input type="number" min="0" value={form.service_downtime_minutes} onChange={(e) => setForm({ ...form, service_downtime_minutes: e.target.value })} /></label></div>{message && <div className={message === 'Incident logged.' ? 'success-box' : 'error-box'}>{message}</div>}<button className="button primary">Save incident evidence</button></form><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Recent records</p><h2>Incident history</h2></div></div>{data.incidents.length ? data.incidents.map((incident) => <div className="incident-row" key={incident.incident_id}><div className="incident-symbol">!</div><div><strong>{incident.incident_id}</strong><small>{incident.asset_id} · {incident.attack_type || 'Unclassified attack'}</small></div><RiskBadge value={incident.compromise_status || 'logged'} /></div>) : <Empty title="No incidents logged" copy="The ledger is ready for evidence from your response team." />}</div></div></section>;
}

function AccessDenied() { return <div className="page-state error-state"><strong>This view is not available for your role.</strong><span>Access is intentionally separated between executive, analyst, and read-only workspaces.</span></div>; }

export default function AppV2() {
  const { user } = useAuth(); const { data, loading, error, syncedAt, refresh } = useWorkspaceData(); const onSimulate = async () => { if (isDemoMode()) { await api.simulateAttack(); refresh(); } }; const demoAction = user.role === 'viewer' ? undefined : onSimulate; const dashboard = user.role === 'viewer' ? <ViewerDashboard data={data} /> : user.role === 'analyst' ? <TechnicalDashboard data={data} onSimulate={demoAction} /> : <ExecutiveDashboard data={data} onSimulate={demoAction} />;
  if (loading) return <div className="loading-screen">Loading secure workspace...</div>;
  return <Shell syncedAt={syncedAt}><>{error && <div className="page-state error-state"><strong>Some live backend data is unavailable.</strong><span>{error}</span></div>}<Routes><Route path="/" element={dashboard} /><Route path="/attacks" element={<AttacksPage data={data} onSimulate={demoAction} />} /><Route path="/assets" element={<AssetsPage data={data} />} /><Route path="/vulnerabilities" element={user.role === 'viewer' ? <AccessDenied /> : <VulnerabilitiesPage data={data} />} /><Route path="/investment" element={user.role === 'admin' ? <InvestmentPageV2 data={data} /> : <Navigate to="/" replace />} /><Route path="/controls" element={user.role === 'admin' ? <ControlsPage data={data} /> : <Navigate to="/" replace />} /><Route path="/audit" element={user.role === 'viewer' || user.role === 'admin' ? <AuditPageV2 data={data} canTamper={user.role === 'admin'} /> : <Navigate to="/" replace />} /><Route path="/analyst" element={user.role === 'viewer' ? <Navigate to="/" replace /> : <AnalystPageV2 />} /><Route path="/incidents" element={user.role === 'viewer' ? <Navigate to="/" replace /> : <IncidentsPage data={data} onRefresh={refresh} />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></></Shell>;
}
